### ISSUE TITLE
付费后，sql更新，邮箱是否会收到最新sql

### ISSUE THREAD

**Issue by zlflying** [otomayss/free-yd#2]

**Comment by otomayss** [comment]
订阅网盘链接就行，我往网盘放新的内容，你的网盘就会同步

**Comment by lfglfg11** [comment]
> 订阅网盘链接就行，我往网盘放新的内容，你的网盘就会同步

大哥，你的网盘链接失效了，我买了后还没下载，没几天你网盘链接失效了，联系你邮箱也不回复

**Comment by otomayss** [comment]
订单号提供一下
---- 回复的原邮件 ----
***@***.***>发送日期2024年09月07日 14:59 ***@***.***> ***@***.***>,
***@***.***>主题Re: [otomayss/free-yd] 付费后，sql更新，邮箱是否会收到最新sql (Issue #2)
订阅网盘链接就行，我往网盘放新的内容，你的网盘就会同步
大哥，你的网盘链接失效了，我买了后还没下载，没几天你网盘链接失效了，联系你邮箱也不回复

**Comment by lfglfg11** [comment]
订单号刚刚已经发你邮箱了

**Comment by lfglfg11** [comment]
> 订单号提供一下 ---- 回复的原邮件 ---- ***@***.***>发送日期2024年09月07日 14:59 ***@***.***> ***@***.***>, ***@***.***>主题Re: [otomayss/free-yd] 付费后，sql更新，邮箱是否会收到最新sql (Issue #2) 订阅网盘链接就行，我往网盘放新的内容，你的网盘就会同步 大哥，你的网盘链接失效了，我买了后还没下载，没几天你网盘链接失效了，联系你邮箱也不回复 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

订单号刚刚已经发你邮箱了
